name: sqltree

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: py36
          python: '3.6'
          toxenv: py36
        - name: py37
          python: '3.7'
          toxenv: py37
        - name: py38
          python: '3.8'
          toxenv: py38
        - name: py39
          python: '3.9'
          toxenv: py39
        - name: py310
          python: '3.10'
          toxenv: py310
        - name: black
          python: '3.9'
          toxenv: black
        - name: pyanalyze
          python: '3.9'
          toxenv: pyanalyze

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: setup tox environment
      run: tox -e ${{ matrix.toxenv }} --notest
    - name: test
      run: tox -e ${{ matrix.toxenv }}
